-- Migration: Cleanup unused tables and columns
-- Generated by Antigravity IDE

-- 1. Drop unused feature tables
DROP TABLE IF EXISTS buddy_requests CASCADE;
DROP TABLE IF EXISTS challenges CASCADE;
DROP TABLE IF EXISTS court_visits CASCADE;
DROP TABLE IF EXISTS venue_presence_events CASCADE;
DROP TABLE IF EXISTS match_health_data CASCADE;
DROP TABLE IF EXISTS match_motion_stats CASCADE;
DROP TABLE IF EXISTS match_player_paths CASCADE;
DROP TABLE IF EXISTS match_rally_stats CASCADE;
DROP TABLE IF EXISTS match_sensor_analytics CASCADE;
DROP TABLE IF EXISTS match_stroke_analytics CASCADE;
DROP TABLE IF EXISTS match_video_calibration CASCADE;
DROP TABLE IF EXISTS player_sleep_data CASCADE;

-- 2. Drop unused columns from matches table
ALTER TABLE matches DROP COLUMN IF EXISTS is_friendly;
